version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecom-website

  user-service:
    build: ./user-service
    networks:
      - ecom-website
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb

  product-service:
    build: ./product-service
    networks:
      - ecom-website
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb

  order-service:
    build: ./order-service
    networks:
      - ecom-website
    environment:
      - MONGO_URI=mongodb://mongo:27017/orderdb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ecom-website

networks:
  ecom-website:
    driver: bridge
