version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecom-website

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - ecom-website
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    networks:
      - ecom-website
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    networks:
      - ecom-website
    environment:
      - MONGO_URI=mongodb://mongo:27017/orderdb

networks:
  ecom-website:
    driver: bridge
