name: ci/cd pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs_on: ubuntu_latest
    steps:
      - name: checkout repo
      uses: actions/checkout@v2
      - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:  
        username: ${{secrets.DOCKDER_USERNAME}}
        password: ${{secrets.DOCKER_PAASWORD}}

      - name: Build and push user service
      uses: docker/build-push-action@v2
      with:
        context: ./user-service
        file: ./user-service/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/user-service:latest

      - name: Build and push product service
      uses: docker/build-push-action@v2
      with:
        context: ./product-service
        file: ./product-service/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/product-service:latest

        - name: Build and push order service
        uses: docker/build-push-action@v2
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/order-service:latest


