name: Build and Deploy to Docker hub

on:
  push:
  branches:
  - master
jobs:
build-and-push:
runs-on:ubuntu-latest
steps:
-name:Checkout repo
uses:actions/checkout@v1
-name:Log in to Docker hub
uses:docker/login-action@v1
with:
username:${{secrets.DOCKER_USERNAME}}
password:${{secrets.DOOCKER_PASSWORD}}
