name: ci/cd pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Build and push product service
        uses: docker/build-push-action@v2
        with:
          context: ./product-service
          file: ./product-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Build and push order service
        uses: docker/build-push-action@v2
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:latest
