name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        
      - name: Run Build
        run: npm run build

  build-and-push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user service
        uses: docker/build-push-action@v2
        with:
          context: ./user-service
          file: ./user-service/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Build and push product service
        uses: docker/build-push-action@v2
        with:
          context: ./product-service
          file: ./product-service/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Build and push order service
        uses: docker/build-push-action@v2
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:latest
